### PR TITLE
Fix my regression (b7d25b0) in sequence loop end/play end handling.

### LINKED ISSUE #136: 3 new tests wrt to the sequence length fail
```
tests/lib/core/e-sequence.c:677:F:BtSequenceExamples:test_bt_sequence_enlarging_length_enlarges_loop:0: Assertion '"loop-end"==24L' failed: "loop-end"==16, 24L==24
tests/lib/core/e-sequence.c:722:F:BtSequenceExamples:test_bt_sequence_shortening_length_truncates_loop:0: Assertion '"loop-end"==8L' failed: "loop-end"==16, 8L==8
tests/lib/core/e-sequence.c:744:F:BtSequenceExamples:test_bt_sequence_shortening_length_disables_loop:0: Assertion '"loop"==(0)' failed: "loop"==1, (0)==0
```

One question:
due to
https://github.com/Buzztrax/buzztrax/blob/master/src/lib/core/sequence.c#L444
will it ever shrink the length?

(Sorry for not pointing this out in the reviews).

### PR DESCRIPTION
**Pull request by dlbeswick**
Also removed "len-patterns" property setter. This property may not agree to set itself to a value that would cause pattern truncation, so the value supplied to g_object_set may not match g_object_get. Not only does this confuse the automated tests (check_readwrite_long_param) but sequence data size management should ideally be a hidden implementation detail.

Fixes #136.

### CODE REVIEW

File: src/lib/core/sequence.c [hunk 1]
```diff
@@ -369,21 +369,64 @@ bt_sequence_get_nonnull_length (const BtSequence * const self) {
   return 0;
 }
 
+/*
+ * bt_sequence_update_post_length_change:
+ * @length: the new value requested for length
+ *
+ * Handles making sure that loop-end doesn't extend past song length, and also
+ * makes sure that loop-end is set to the song length, then the loop-end is
```
Comment (ensonic) [inline src/lib/core/sequence.c:377]: sure that **if** loop-end is set ...

File: src/lib/core/sequence.c [hunk 2]
```diff
@@ -369,21 +369,64 @@ bt_sequence_get_nonnull_length (const BtSequence * const self) {
...
+ * when their song length changes, so the previous loop-end doesn't hang around
+ * floating somewhere in the middle of the song.
+ *
+ * Also sets play-end appropriately when length is to change.
+ *
+ * Should be called after self->length changes.
+ */
+static void
+bt_sequence_post_length_change (const BtSequence * const self,
+    guint old_length)
```
Comment (ensonic) [inline src/lib/core/sequence.c:388]: gulong old_length
to avoid truncating

File: src/lib/core/sequence.c [hunk 3]
```diff
@@ -369,21 +369,64 @@ bt_sequence_get_nonnull_length (const BtSequence * const self) {
...
-static void
+void
 bt_sequence_resize_data_length (const BtSequence * const self, const gulong length)
 {
   const gulong tracks = self->priv->tracks;
 
   const gulong old_length = self->priv->len_patterns;
   
-  // try to shrink the pattern up to the row having the final non-empty pattern cell
+  /* Try to shrink the pattern up to the row having the final non-empty pattern
```
Comment (ensonic) [inline src/lib/core/sequence.c:425]: s/pattern/sequence/

**Review by ensonic — COMMENTED** [review]
Thanks for the follow up. Only a few nits.
